project_name: nats-server
version: 2

builds:
  - main: .
    id: nats-server
    binary: nats-server
    ldflags:
      - -w -X github.com/nats-io/nats-server/v2/server.gitCommit={{.ShortCommit}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

release:
  disable: true

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.nightly
    skip_push: false
    build_flag_templates:
      - '--build-arg=VERSION={{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}'
    image_templates:
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}
      - ghcr.io/nats-io/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}
      - ghcr.io/nats-io/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}
    extra_files:
      - docker/nats-server.conf

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

snapshot:
  version_template: '{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}'
