project_name: nats-server
version: 2

builds:
  - main: .
    id: nats-server
    binary: nats-server
    ldflags:
      - -w -X github.com/nats-io/nats-server/v2/server.gitCommit={{.ShortCommit}}
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

release:
  disable: true

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: docker/Dockerfile.nightly
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/amd64'
      - '--build-arg=VERSION={{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}'
    image_templates:
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-amd64
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}-amd64
    extra_files:
      - docker/nats-server.conf
  - goos: linux
    goarch: arm64
    dockerfile: docker/Dockerfile.nightly
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/arm64'
      - '--build-arg=VERSION={{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}'
    image_templates:
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-arm64
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}-arm64
    extra_files:
      - docker/nats-server.conf

docker_manifests:
  - name_template: synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}
    image_templates:
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-amd64
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-arm64
  - name_template: synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}
    image_templates:
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}-amd64
      - synadia/nats-server:{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}-arm64


checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256

snapshot:
  version_template: '{{ if ne .Branch "main" }}{{ replace .Branch "/" "-" }}{{ else }}nightly{{ end }}-{{ time "20060102" }}'
