name: Nightly Docker Releaser
description: Builds nightly docker images

inputs:
  hub_username:
    description: Docker hub username
    required: true

  hub_password:
    description: Docker hub password
    required: true

  workdir:
    description: The working directory for actions requiring it
    required: true

runs:
  using: composite
  steps:
    - name: Log in to Docker Hub
      shell: bash
      run: docker login -u "${{ inputs.hub_username }}" -p "${{ inputs.hub_password }}"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Build and push Docker images
      # Use commit hash here to avoid a re-tagging attack, as this is a third-party action
      # Commit 9ed2f89a662bf1735a48bc8557fd212fa902bebf = tag v6.1.0
      uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf
      with:
        workdir: "${{ inputs.workdir }}"
        version: ~> v2
        args: release --skip=announce,validate --config .goreleaser-nightly.yml
