@startuml
participant "APP" as app
participant "NATS" as  nats
box "Internal Components"
participant "Oauth \nAccess Manager" as ar
participant "Data server" as ds
end box
participant "Oauth2" as oauth

ds-> nats : connect(user:pass)
nats->nats: lookup local User
nats-->ds: success
ar-> nats : connect(user:pass)
nats->nats: lookup local User
nats-->ar: success
app -> oauth : user authorize application to access data for certain scopes (eg. myvechile.telematics)
oauth-->app: token
app->nats : connect(token)
nats->nats: request(authenticator, token)
nats->ar : authenticate user and get permission based on token
ar->oauth:validate token
oauth-->ar: scope for this app
ar-->nats:User and permission(eg myvechile.telematics.<uid>)
nats-->app: success

app->nats: request(myvechile.telematics.<uid>)
nats->nats: check permission
nats->ds: get data
ds->nats: publish data
nats->app: data

@enduml