apiVersion: v2
name: nats-leafnode
description: A Helm chart for CPS deployment of a NATS Leaf Node
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0
# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

dependencies:
  - name: nats
    version: 1.3.13
    repository: "https://nats-io.github.io/k8s/helm/charts/"