name: NATS Server Releases
on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  run:
    name: GitHub Release
    runs-on: ${{ vars.GHA_WORKER_RELEASE || 'ubuntu-latest' }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"

      - name: Check version matches tag
        env:
          TRAVIS_TAG: ${{ github.ref_name }}
        run: |
          go test -race -v -run=TestVersionMatchesTag ./server -ldflags="-X=github.com/nats-io/nats-server/v2/server.serverVersion=$TRAVIS_TAG" -count=1 -vet=off

      - name: Install cosign
        # Use commit hash here to avoid a re-tagging attack, as this is a third-party action
        # Commit ba7bc0a3fef59531c69a25acd34668d6d3fe6f22 = tag v4.1.0
        uses: sigstore/cosign-installer@ba7bc0a3fef59531c69a25acd34668d6d3fe6f22

      - name: Install syft
        # Use commit hash here to avoid a re-tagging attack, as this is a third-party action
        # Commit 57aae528053a48a3f6235f2d9461b05fbcb7366d = tag v0.23.1
        uses: anchore/sbom-action/download-syft@57aae528053a48a3f6235f2d9461b05fbcb7366d
        with:
          syft-version: "v1.42.2"

      - name: Create release
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
