name: Stale Issues
on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-label: stale
          stale-pr-label: stale
          days-before-stale: 56 # Mark stale after 8 weeks (56 days) of inactivity
          days-before-close: -1 # Disable auto-closing
          exempt-all-milestones: true # Any issue/PR within a milestone will be omitted
